allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

def newBuildDir = rootProject.layout.buildDirectory.dir("../../build").get()
rootProject.layout.buildDirectory.value(newBuildDir)

subprojects {
    def newSubprojectBuildDir = newBuildDir.dir(project.name)
    project.layout.buildDirectory.value(newSubprojectBuildDir)
}

subprojects {
    project.evaluationDependsOn(":app")
    def configureSubproject = { p ->
        if (p.plugins.hasPlugin("com.android.application") || p.plugins.hasPlugin("com.android.library")) {
            p.android {
                testOptions {
                    unitTests {
                        includeAndroidResources = false
                    }
                }
            }
        }
    }
    if (project.state.executed) {
        configureSubproject(project)
    } else {
        project.afterEvaluate { p ->
            configureSubproject(p)
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
